version: '3'

services:
  back:
    build: back/
    environment:
      - DB_USER
      - DB_PASS
      - DB_HOST=database
      - DB_PORT
      - DB_NAME
      - API_PORT
      - API_HOST=0.0.0.0
    ports:
      - "${API_PORT}:${API_PORT}"
    networks:
      - backend
      - application

  database:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    networks:
      - backend
    volumes:
      - database:/var/lib/postgresql/data

networks:
  backend:
  application:

volumes:
  database:
