version: '3'

services:
  database:
    image: postgres
    environment:
      - POSTGRES_DB=$DB_NAME
      - POSTGRES_PASSWORD=$DB_PASS
      - POSTGRES_USER=$DB_USER

  api:
    build: ..
    environment:
      - DB_NAME
      - DB_USER
      - DB_PASS
      - DB_PORT
      - DB_HOST=database
      - PORT=$API_PORT
    ports:
      - "${API_PORT}:${API_PORT}"