# Generated by Django 4.1.7 on 2023-03-16 13:41

from django.db import migrations, models
import django_enum.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=72)),
                ('state', django_enum.fields.EnumCharField(choices=[('NeufA', 'NeufA'), ('NeufS', 'NeufS'), ('TBE', 'TBE'), ('BE', 'BE'), ('Satisfaisant', 'Satisfaisant')], max_length=12)),
                ('size', django_enum.fields.EnumCharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL')], max_length=2)),
                ('brand', models.CharField(max_length=24)),
                ('image_url', models.URLField()),
                ('description', models.TextField()),
                ('buy_price', models.PositiveIntegerField()),
                ('sold', models.BooleanField(default=False)),
                ('sold_price', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
    ]
