on:
  workflow_call:
    secrets:
      REGISTRY_TOKEN:
        required: true

    inputs:        
      app:
        type: string 
        description: Application name
        required: true

      tag:
        type: string
        description: Tag to give to the built image
        required: true

      context:
        type: string
        description: Context to use on the build
        required: false
        default: '.'

      dockerfile:
        type: string
        description: Dockerfile to use to built the image
        required: false
        default: 'Dockerfile'


jobs:
  build_publish:
    name: Build and publish image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository.
        uses: actions/checkout@v3
  
      - name: "Setup Docker Buildx"
        uses: docker/setup-buildx-action@v1
  
      - name: "Login to GitHub Registry"
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: TomChv
          password: ${{ secrets.REGISTRY_TOKEN }}
  
      - name: Format Docker tag
        uses: actions/github-script@v6
        id: format-docker-tag
        with:
          result-encoding: string
          script: | 
            const tags = ${{ inputs.tag }}

            const result = tags
              .split(",") // Split by comma
              .map((e) => e.trim()) // Remove useless space
              .map((e) => `ghcr.io/tomchv/playground/${{ inputs.app }}:${e}`) // Convert tag to its complete tag name
              .join(", ") // Rebuild string with ,

            console.log(`Release docker image with tag: ${result}`)
            return result
  
      - name: Build & Push image
        uses: docker/build-push-action@v4
        with:
          context: ${{ inputs.context }}
          file: ${{ inputs.dockerfile }}
          push: true
          tags: ${{ steps.format-docker-tag.outputs.result }}