name: Production integration

on:
  workflow_dispatch:
    inputs:
      bump:
        description: |
          Degree of version bump 'patch|minor|major' (should match with targeted version).
          If you go from v1.0.0 to v1.0.1, it a patch ; from v1.0.0 to v1.1.0 is minor
          and from v1.0.0 to v2.0.0 is a major release.
        required: true

jobs:
  build_test_stack:
    strategy:
      matrix:
        stack: 
        - app1
        - app2
    name: Build ${{ matrix.stack }}
    uses: tomchv/playground/.github/workflows/build-publish-workflows.yml@main
    needs: release-version
    secrets:
      REGISTRY_TOKEN: ${{ secrets.REGISTRY_TOKEN }}
    with:
      app: ${{ matrix.stack }}
      tag: latest, ${{ needs.release-version.outputs.tag }}
      context: version-releaser/${{ matrix.stack }}
      dockerfile: version-releaser/${{ matrix.stack }}/Dockerfile

  release-version:
    name: Release new version
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    outputs:
      tag: ${{ steps.release.outputs.tag_name }}
    steps:
      - name: Release version
        uses: rymndhng/release-on-push-action@master
        id: release
        with:
          bump_version_scheme: ${{ github.event.inputs.bump }}