name: Production integration

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version of the new release (e.g., v1.0.0)'
        required: true
      bump:
        description: |
          Degree of version bump 'patch|minor|major' (should match with targeted version).
          Example:
            - v1.0.0 -> v1.0.1: patch
            - v1.0.0 -> v1.1.0: minor
            - v1.0.0 -> v2.0.0: major
        required: true

jobs:
  build_test_stack:
    strategy:
      matrix:
        stack: 
        - app1
        - app2
    name: Build ${{ matrix.stack }}
    uses: tomchv/playground/.github/workflows/build-publish-workflows.yml@main
    secrets:
      REGISTRY_TOKEN: ${{ secrets.REGISTRY_TOKEN }}
    with:
      app: ${{ matrix.stack }}
      tag: latest, ${{ github.event.inputs.version }}
      context: version-releaser/${{ matrix.stack }}
      dockerfile: version-releaser/${{ matrix.stack }}/Dockerfile

  release-version:
    name: Release new version
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Release version
        uses: rymndhng/release-on-push-action@master
        with:
          bump_version_scheme: ${{ github.event.inputs.bump }}