name: Auto rebase

on:
    # Run on every push on every branch
    push:
        branches-ignore:
            # Ignore branches automatically created by github-rebase
            - rebase-pull-request**
            - cherry-pick-rebase-pull-request**

jobs:
    auto-rebase:
        name: AutoRebase
        runs-on: ubuntu-latest
        steps:
            - uses: Label305/AutoRebase@v0.1
              with:
                  github_token: ${{ secrets.AUTO_REBASE_PAT }}